services:
  postgres:
    image: postgres:latest
    container_name: vertx_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/create_app.sql:/docker-entrypoint-initdb.d/1_create_app.sql
      - ./src/main/resources/db/create_status.sql:/docker-entrypoint-initdb.d/2_create_status.sql
      - ./src/main/resources/db/init_app.sql:/docker-entrypoint-initdb.d/3_init_app.sql
      - ./src/main/resources/db/create_history.sql:/docker-entrypoint-initdb.d/4_create_history.sql

  vertx_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_vertx
    depends_on:
      - postgres
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
      SENDGRID_PWD: changehere
    ports:
      - "8888:8888"
    restart: always
